### ISSUE TITLE
Running the application 

### ISSUE THREAD

**Issue by shubhankargupta** [olinations/crud-starter-frontend#1]
Hi,

Since I am new to full stack development, I have a few queries regarding running the application.
Do I have to enter "npm start" commands both in frontend and backend folders? When I use "npm start" for frontend, it is running on port 3000. How should I run it on port 3001? 
Also, in what sequence should I run the commands? And, on what port should the postgresql should be running...port 3000 or another port?

**Comment by kinxiel** [comment]
Hi,

You need to navigate to inside the api backend folder first, then npm start there. On a separate terminal window, navigate to the front end folder, then npm start there. Sine by default, the backend repo uses port 3000, react-scripts will ask you if you would like to run on a different port. Answer `Y` here and React will open at port 3001 be default.
